steps:
  - id: 'Deploy pre-built version (Deprecated)'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    entrypoint: gsutil
    args:
      [
        '-m',
        'rsync',
        '-r',
        'gs://gr4vy-embed-cdn-version-repository/${COMMIT_SHA}',
        'gs://$_ARTIFACT_STORAGE_BUCKET',
      ]
    waitFor: ['-']

  - id: 'Deploy pre-built version'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    entrypoint: gsutil
    args:
      [
        '-m',
        'rsync',
        '-d',
        '-r',
        'gs://gr4vy-embed-cdn-version-repository/${COMMIT_SHA}',
        'gs://$_ARTIFACT_STORAGE_BUCKET/embed/latest/',
      ]
    waitFor: ['-']

  - id: 'Add commit SHA label to storage bucket'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    entrypoint: gcloud
    args:
      [
        'storage',
        'buckets',
        'update',
        'gs://$_ARTIFACT_STORAGE_BUCKET/',
        '--update-labels=commit_sha=${COMMIT_SHA}',
      ]
    waitFor: ['Deploy pre-built version (Deprecated)', 'Deploy pre-built version']

  - id: 'Invalidate CDN cache'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    entrypoint: bash
    args:
      - '-eEuo'
      - pipefail
      - '-c'
      - |-
        if [ ${_GR4VY_ENV} = "production" ]; then
          HOST_DOMAIN=${_GR4VY_ID}.gr4vy.app
        else
          HOST_DOMAIN=${_GR4VY_ENV}.${_GR4VY_ID}.gr4vy.app
        fi
        gcloud compute url-maps invalidate-cdn-cache $_URL_MAP_SHARED --host="cdn.$${HOST_DOMAIN}" --path='/embed/latest/*' --async --project $PROJECT_ID
        gcloud compute url-maps invalidate-cdn-cache $_URL_MAP_SHARED --host="cdn.$${HOST_DOMAIN}" --path='/embed.latest.js' --async --project $PROJECT_ID
    waitFor:
      ['Deploy pre-built version (Deprecated)', 'Deploy pre-built version']

substitutions:
  _GR4VY_ID: ${PROJECT_ID%-*}
  _GR4VY_ENV: 'sandbox'
  _ARTIFACT_STORAGE_BUCKET: ${PROJECT_ID}-cdn-${_GR4VY_ENV}
  _URL_MAP_SHARED: ${_GR4VY_ID}-${_GR4VY_ENV}-url-map

options:
  dynamic_substitutions: true
  substitution_option: 'ALLOW_LOOSE'
  machineType: 'E2_MEDIUM'
